name: Create release to make .exe published.

on:
    push:
        branches: [ "main" ]
    workflow_dispatch:

jobs:
    build:
        runs-on: windows-latest
        steps:
            # Checkout the repo
          - name: Checkout
            uses: actions/checkout@v3
            with:
                fetch-depth: 1
            # Publish self
          - name: Create the app package
            run: cargo run -- --publish
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
